//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package info.juanmendez.filemanipulation;

import android.content.Context;
import android.content.Intent;

public final class DownloadReceiver_
    extends DownloadReceiver
{

    private Context context_;

    private void init_() {
        prefs = new DownloadPrefs_(context_);
    }

    @Override
    public void onReceive(Context context, Intent intent) {
        context_ = context;
        init_();
        super.onReceive(context, intent);
    }

}
