//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package info.juanmendez.filemanipulation;

import android.content.Context;
import info.juanmendez.filemanipulation.FileControl.iFileInterface;
import org.androidannotations.api.BackgroundExecutor;

public final class FileControl_
    extends FileControl
{

    private Context context_;

    private FileControl_(Context context) {
        context_ = context;
        init_();
    }

    public static FileControl_ getInstance_(Context context) {
        return new FileControl_(context);
    }

    private void init_() {
        prefs = new DownloadPrefs_(context_);
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

    @Override
    public void removeFile(final String fileName, final iFileInterface i) {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    FileControl_.super.removeFile(fileName, i);
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

}
