//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package info.juanmendez.filemanipulation;

import android.content.Context;
import android.os.Handler;
import android.os.Looper;

public final class MenuPrefs_
    extends MenuPrefs
{

    private Context context_;
    private Handler handler_ = new Handler(Looper.getMainLooper());

    private MenuPrefs_(Context context) {
        context_ = context;
        init_();
    }

    public static MenuPrefs_ getInstance_(Context context) {
        return new MenuPrefs_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

    @Override
    public void showDownload() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                MenuPrefs_.super.showDownload();
            }

        }
        );
    }

    @Override
    public void showRestore() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                MenuPrefs_.super.showRestore();
            }

        }
        );
    }

}
