//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package info.juanmendez.filemanipulation;

import android.content.ComponentName;
import android.content.Context;
import android.content.Intent;
import android.support.v4.app.Fragment;

public final class UnzipService_
    extends UnzipService
{


    public static UnzipService_.IntentBuilder_ intent(Context context) {
        return new UnzipService_.IntentBuilder_(context);
    }

    public static UnzipService_.IntentBuilder_ intent(Fragment supportFragment) {
        return new UnzipService_.IntentBuilder_(supportFragment);
    }

    private void init_() {
        prefs = new DownloadPrefs_(this);
    }

    @Override
    public void onCreate() {
        init_();
        super.onCreate();
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, UnzipService_.class);
        }

        public IntentBuilder_(Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, UnzipService_.class);
        }

        public Intent get() {
            return intent_;
        }

        public UnzipService_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public ComponentName start() {
            return context_.startService(intent_);
        }

        public boolean stop() {
            return context_.stopService(intent_);
        }

    }

}
